[package]
name = "nes_emulator"
version = "0.1.0"
authors = ["Dante Ruiz <danteruiz102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = { version = "0.41.0"}
bitflags = { version = "1.3.2" }
